FROM golang:1.25-alpine3.22

# Install system packages
RUN apk update && apk add --no-cache git protobuf make build-base

# Install Go tools globally
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

# Set PATH for installed Go binaries
ENV PATH="$PATH:$(go env GOPATH)/bin"
